spring:
  application:
    name: treinamento
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop

deploy:
    swagger_name: openapi.json

info:
  app:
    name: 'treinamento'
    description: 'Parent pom providing dependency and plugin management for applications built with Maven'
    version: '1.0'
    contact:
      name: 'ALINE ABREU'
      email: 'aline.s.abreu@bradesco.com.br'
      url: 'http://localhost:8080'
    server:
      url: 'http://localhost:8080'
    external-documentation:
      description: 'Documentation'
      url: 'http://localhost:8080'

server:
  port: ${SERVER_PORT:8080}
  servlet:
    contextPath: /

springdoc:
  pathsToMatch: /**
  swagger-ui:
    enabled: true
    tagsSorter: alpha